In [1]:
import os

In [2]:
BASE_PATH = '../ord_reg'
os.chdir(BASE_PATH)

In [3]:
!pwd

/Users/michaelka/Developer/ml/projects/ord_reg/ord_reg


In [45]:
model.model_name=resnet18, efficientnet_b0, resnet18d, resnest14d, seresnet50

train.num_epochs=3
save_checkpoint=true

optimizer=sgd
optimizer.lr=7e-5
optimizer.lr=1e-4
optimizer.lr=3e-4
optimizer.lr=1e-3

optimizer.weight_decay=1e-6

train.batch_size_train=16
    
# scheduler.milestones=[1]
scheduler.gamma=0.2
    
+experiment=baseline
+experiment=label_bin
+experiment=coral

In [ ]:
python main.py +experiment=label_bin model.model_name=resnest14d optimizer.lr=3e-4

In [ ]:
python main.py +experiment=baseline train.num_epochs=5 train.batch_size_train=128 save_checkpoint=true seed=1

In [94]:
# !python main.py +experiment=baseline model.encoder.model_name=resnet18d

In [ ]:
bs_resnet18_lr_0.0001 acc = 0.49250, qwk = 0.41622
lb_resnest14d_lr_0.0003 acc = 0.46500, qwk = 0.53138

In [96]:
import numpy as np

## baseline

In [ ]:
python main.py +experiment=baseline model.encoder.model_name=resnest14d save_checkpoint=true seed=1

In [ ]:
python main.py +experiment=baseline optimizer.lr=3e-4 save_checkpoint=true seed=1

1: acc = 0.52500, qwk = 0.55848
2: acc = 0.52000, qwk = 0.54460
3: acc = 0.49250, qwk = 0.50847

1: Inconsistency in predictions: 385/400
2: Inconsistency in predictions: 392/400
3: Inconsistency in predictions: 389/400

In [ ]:
python main.py +experiment=baseline train.batch_size_train=128 save_checkpoint=true seed=1
bs_resnet18_lr:0.0001_bs:128

1: acc = 0.48000, qwk = 0.52252
2: acc = 0.46000, qwk = 0.50215
3: acc = 0.50250, qwk = 0.47231

In [ ]:
Inconsistency in predictions: 395/400, total: 765

In [116]:
np.mean([0.52252, 0.50215, 0.47231])

0.49899333333333334

In [ ]:
python main.py +experiment=baseline model.encoder.model_name=resnet18d train.batch_size_train=32 optimizer.lr=1e-4 save_checkpoint=true seed=1
bs_resnet18d_lr:0.0001_bs:32
        
1: acc = 0.45750, qwk = 0.40524
2: acc = 0.45250, qwk = 0.40233
3: acc = 0.46500, qwk = 0.34887


In [ ]:
python main.py +experiment=baseline model.encoder.model_name=resnet18d train.batch_size_train=32 optimizer.lr=3e-4 save_checkpoint=true seed=1
bs_resnet18d_lr:0.0003_bs:32
        
1: acc = 0.49250, qwk = 0.50046
2: acc = 0.47750, qwk = 0.35084
3: acc = 0.49250, qwk = 0.35841

In [ ]:
python main.py +experiment=baseline model.encoder.model_name=resnet18d train.batch_size_train=128 optimizer.lr=1e-4 save_checkpoint=true seed=1
bs_resnet18d_lr:0.0001_bs:128
        
1: acc = 0.40500, qwk = 0.25682
2: acc = 0.43500, qwk = 0.31251

In [ ]:
python main.py +experiment=baseline model.encoder.model_name=efficientnet_b0 train.batch_size_train=128 optimizer.lr=1e-4 save_checkpoint=true seed=1
bs_efficientnet_b0_lr:0.0001_bs:128


## label_bin

In [ ]:
python main.py +experiment=label_bin save_checkpoint=true seed=1

In [ ]:
python main.py +experiment=label_bin optimizer.lr=3e-4 save_checkpoint=true seed=1
y_pred = (outputs > 0).sum(1)

acc = 0.46500, qwk = 0.54456
acc = 0.49500, qwk = 0.54620
acc = 0.48250, qwk = 0.47670

Inconsistency in predictions: 41/400
Inconsistency in predictions: 254/400
Inconsistency in predictions: 147/400

In [ ]:
python main.py +experiment=label_bin train.batch_size_train=128 save_checkpoint=true seed=1
lb_resnet18_lr:0.0001_bs:128
        
1: acc = 0.44750, qwk = 0.49567
2: acc = 0.41500, qwk = 0.52916
 [90 48 27  9  0]
 [ 8 13 21  4  0]
 [ 7 27 39 19  0]
 [ 2  7 35 24  0]
 [ 1  5  6  8  0]
# it's hard to have something in the last col

3: acc = 0.45750, qwk = 0.50466


Inconsistency in predictions: 186/400, total: 282
Inconsistency in predictions: 232/400, total: 281

In [ ]:
y_pred = (outputs > 0).sum(1)

1: acc = 0.51000, qwk = 0.55381
2: acc = 0.47750, qwk = 0.54938
3: acc = 0.51250, qwk = 0.58397

In [100]:
np.mean([0.55381, 0.54938, 0.58397])

0.5623866666666667

In [ ]:
python main.py +experiment=label_bin save_checkpoint=true

# coral

In [ ]:
python main.py +experiment=coral save_checkpoint=true seed=1

In [ ]:
python main.py +experiment=coral optimizer.lr=3e-4 save_checkpoint=true seed=1

1: acc = 0.40500, qwk = 0.44044
2: acc = 0.47250, qwk = 0.50362

y_pred = (outputs > 0).sum(1)
1: acc = 0.42500, qwk = 0.32534
2: acc = 0.42500, qwk = 0.46797

In [ ]:
python main.py +experiment=coral train.batch_size_train=128 save_checkpoint=true seed=1
cr_resnet18_lr:0.0001_bs:128
        
1: acc = 0.42250, qwk = 0.52879
2: acc = 0.45000, qwk = 0.56074
3: acc = 0.46250, qwk = 0.51352

In [99]:
np.mean([0.52879, 0.56074, 0.51352])

0.53435

In [ ]:
y_pred = (outputs > 0).sum(1)

1: acc = 0.40750, qwk = 0.49566
 [129   9  13   7  16]
 [ 13   3  11  12   7]
 [ 20  11  12  15  34]
 [  6   5   5  11  41]
 [  3   2   5   2   8]
# predict more higher grades

acc = 0.45500, qwk = 0.48814
acc = 0.44750, qwk = 0.37769

In [ ]:
CoralLoss
y_pred = y_prob.sum(1).round()

acc = 0.41000, qwk = 0.54560
acc = 0.47000, qwk = 0.56800
acc = 0.44750, qwk = 0.51788

In [98]:
np.mean([0.54560, 0.56800, 0.51788])

0.5438266666666666

In [ ]:
CoralLoss
y_pred = (outputs > 0).sum(1)

acc = 0.42500, qwk = 0.51928

## pretrained=false

In [ ]:
python main.py +experiment=baseline model.encoder=base

In [ ]:
python main.py +experiment=baseline train.num_epochs=10 model.encoder.pretrained=false train.batch_size_train=128 save_checkpoint=true seed=1
bs_resnet18_lr:0.0001_bs:128
pretrained=false
        
1: acc = 0.54250, qwk = 0.54130
 [132   0  33   9   0]
 [ 15   0  24   7   0]
 [ 18   0  60  14   0]
 [  5   0  38  25   0]
 [  4   0  12   4   0]
2: acc = 0.53500, qwk = 0.55065


In [ ]:
python main.py +experiment=label_bin train.num_epochs=10 model.encoder.pretrained=false train.batch_size_train=128 save_checkpoint=true seed=1

1: acc = 0.43750, qwk = 0.49902
 [94 49 31  0  0]
 [ 6 21 19  0  0]
 [ 9 23 60  0  0]
 [ 2  6 60  0  0]
 [ 2  5 13  0  0]

train.num_epochs=20    
2: acc = 0.46500, qwk = 0.54580
 [101  39  34   0   0]
 [  8  12  26   0   0]
 [  7  14  71   0   0]
 [  2   3  61   2   0]
 [  1   4  15   0   0]

train.num_epochs=10
optimizer.lr=3e-4
acc = 0.40500, qwk = 0.48852
 [66 61 43  4  0]
 [ 5  8 32  1  0]
 [ 8  1 77  6  0]
 [ 1  2 54 11  0]
 [ 1  2 15  2  0]


In [ ]:
python main.py +experiment=label_bin train.num_epochs=10 model.encoder.pretrained=false train.batch_size_train=128 optimizer.lr=3e-4 save_checkpoint=true seed=1


## Simple model

In [ ]:
python main.py +experiment=baseline model/encoder=base train.num_epochs=30 save_checkpoint=true seed=1
bs_base_lr:0.0001_bs:128

1: acc = 0.54500, qwk = 0.54636
Inconsistency in predictions: 394/400
    
2: acc = 0.54500, qwk = 0.56221
Inconsistency in predictions: 388/400
 [131   0  23  20   0]
 [ 12   0  21  13   0]
 [ 17   0  49  26   0]
 [  4   0  26  38   0]
 [  3   0   4  13   0]

3: acc = 0.54750, qwk = 0.56618
    
    
4: acc = 0.54250, qwk = 0.54667

In [113]:
np.mean([0.54636, 0.56221, 0.54667])

0.5517466666666666

In [ ]:
python main.py +experiment=label_bin model/encoder=base train.num_epochs=30 save_checkpoint=true seed=1
python main.py +experiment=label_bin train.num_epochs=30 save_checkpoint=true seed=1
lb_base_lr:0.0001_bs:128
        
1: acc = 0.52750, qwk = 0.58684
Inconsistency in predictions: 0/400    
 [126   3  43   2   0]
 [ 10   2  31   3   0]
 [ 10   6  70   6   0]
 [  2   2  51  13   0]
 [  2   1  11   6   0]]

acc = 0.51250, qwk = 0.53363

acc = 0.52250, qwk = 0.56444

acc = 0.52000, qwk = 0.55422

In [112]:
np.mean([0.58684, 0.56444, 0.55422])

0.5685000000000001

In [ ]:
python main.py +experiment=coral train.num_epochs=30 save_checkpoint=true seed=1

python main.py +experiment=coral train.num_epochs=30 optimizer.lr=3e-4 save_checkpoint=true seed=1
1: acc = 0.46250, qwk = 0.53814
2: acc = 0.48000, qwk = 0.53729
 [117  17  40   0   0]
 [  9   6  31   0   0]
 [  7  16  69   0   0]
 [  2   4  62   0   0]
 [  1   5  14   0   0]

python main.py +experiment=coral train.num_epochs=30 optimizer.lr=5e-4 save_checkpoint=true seed=1
1: acc = 0.46500, qwk = 0.54060
2: acc = 0.49000, qwk = 0.55438

## + nn.Linear

In [ ]:
python main.py +experiment=coral train.num_epochs=30 optimizer.lr=5e-4 save_checkpoint=true seed=1
+ nn.Linear

acc = 0.48750, qwk = 0.56251
acc = 0.48500, qwk = 0.56154

In [ ]:
python main.py +experiment=baseline train.num_epochs=30 save_checkpoint=true seed=1
+ nn.Linear

1: acc = 0.52750, qwk = 0.55729
2: acc = 0.53750, qwk = 0.55408

In [ ]:
python main.py +experiment=label_bin train.num_epochs=30 save_checkpoint=true seed=1

1: acc = 0.50750, qwk = 0.55786

## resnext50_32x4d

In [ ]:
resnext50_32x4d
python main.py +experiment=label_bin train.num_epochs=5  optimizer.lr=5e-4 model.encoder.model_name=resnext50_32x4d save_checkpoint=true seed=1

# Other

In [ ]:
tensorboard --logdir=/Users/michaelka/Developer/ml/projects/ord_reg/ord_reg/outputs/2021-11-30/12-05-00/runs
tensorboard --logdir=/Users/michaelka/Developer/ml/projects/ord_reg/ord_reg/outputs/runs

In [78]:
import numpy as np

In [79]:
-np.log(1/5)

1.6094379124341003

In [102]:
import timm
from pprint import pprint
model_names = timm.list_models(pretrained=True)
pprint(model_names)

['adv_inception_v3',
 'cait_m36_384',
 'cait_m48_448',
 'cait_s24_224',
 'cait_s24_384',
 'cait_s36_384',
 'cait_xs24_384',
 'cait_xxs24_224',
 'cait_xxs24_384',
 'cait_xxs36_224',
 'cait_xxs36_384',
 'coat_lite_mini',
 'coat_lite_small',
 'coat_lite_tiny',
 'coat_mini',
 'coat_tiny',
 'convit_base',
 'convit_small',
 'convit_tiny',
 'cspdarknet53',
 'cspresnet50',
 'cspresnext50',
 'deit_base_distilled_patch16_224',
 'deit_base_distilled_patch16_384',
 'deit_base_patch16_224',
 'deit_base_patch16_384',
 'deit_small_distilled_patch16_224',
 'deit_small_patch16_224',
 'deit_tiny_distilled_patch16_224',
 'deit_tiny_patch16_224',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'densenetblur121d',
 'dla34',
 'dla46_c',
 'dla46x_c',
 'dla60',
 'dla60_res2net',
 'dla60_res2next',
 'dla60x',
 'dla60x_c',
 'dla102',
 'dla102x',
 'dla102x2',
 'dla169',
 'dm_nfnet_f0',
 'dm_nfnet_f1',
 'dm_nfnet_f2',
 'dm_nfnet_f3',
 'dm_nfnet_f4',
 'dm_nfnet_f5',
 'dm_nfnet_f6',
 'dpn68',
 'dpn

In [105]:
model_name = 'resnest14d'
model = timm.create_model(model_name, pretrained=False)

In [106]:
model

ResNet(
  (conv1): Sequential(
    (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  )
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): ResNestBottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act1): ReLU(inplace=True)
      (con